apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCqMgmQt+YynoGwgY+00XfERDyM9s2w11JUKOa3s76rOsv9+djhNdLF2Rk147iJoNaxFRKhezfrVhFb6SzZNFj+qDg3nkATNiJWPZ2DD+ASxciHQmSkY6bpoVNNAJBtpZNRRi/w7rAPZ1e4B4/TBJOBVZ4QuWxMNOjVYLpidv/c0YsIpckRDMUarJeCB6P/MQQknWC4SHyUCDD//H2k19MeYmZtIXgSJ9xNg80QgnCIIRPqbcoiJVw+enwCk21u6yv01pijyI95MP1GEMeWEDt7IRzbbjcSZT5wquXhzxb7q7+r6ggAv2jjVJ/Mljh5m67SfI57y409a3ZlYtDzNmAadcN48glvwSQ2L5DNnvbUix3Jbqmz4reZoBi6fVw5Xs+6IHOKOre/7paftXW7h+YI8+SmK0ZlK99x3r4NTLUgJ7lPltOrdrNyV0jorgjUwnb1mnfcWvM0kRnEtgGmyZQbfmVAkNX5ABHoxQn7Abq4j6Dn8cSJFUyBrEmXlkBbyLYxlXPIVY2rI2p6eIax27h+A7PPoCPZBJOfGEGLMTm3Bsn64xuuxNQjPLePJM6AxxaPwSVqKaSoOhd4FUf0dlEWQZv9LsApyaYzC20sCqL+M+fqNiduxF9Xky0Rxy2UjfeT9oUhRaUOihBUHbgLF5bRPTa8atv/C/WIiHTQ1DSi8cpMJVFGf/lJjuQjbDKrZlwm/KhT1gXiXpEHmsEe/WozjJo2PFt0Y+EI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

