apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:vOE4DBtsu6dL/NAzbLdn56zMLygDNa2ceA==,iv:5rUCaUwniRQ6TJbW+8KuGxhOwFLrQjP2I/DQH423unE=,tag:CLWeJ8xzBsG4u3D60W9QKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-24T12:52:43Z"
    mac: ENC[AES256_GCM,data:snCWwD1inYArTSlSocmWo/rdpY6uF12ovnQ16pvgVpT3xnfdLbvemLK8hy+czI6tejqwJJpFaXJFAmHWnHDLSl6ohESm+Ge0+00gHBTuxyptafqsdCO9RzGJPhHC8h0pfbXaAE0vsgdFwZ35P9bMVffydWLWFxboLwJH3JDYVuY=,iv:1MLb+6DcoasSpUIacAVrkrT49OlLlF57NJexR2xXJZA=,tag:L8Q4ksI5hADu4AFpXYzkxw==,type:str]
    pgp:
        - created_at: "2025-06-24T12:52:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyUP4FRMPKAzAQv+K5Cj1o/2niINNo3+h9vU1PykwBdnYsanlSjC8hvI+v9i
            8ezrUFXT0vd/Xpx7jLsOthOBDeFzrNAyaH8XH13L+Pg6E6tYFAep4G0T3w6Sn6v1
            Ptg9leO9cjWUEjVKSO1z9BnKZfxVoT2zhmmQJlXC4aZhFJZiFcGuzJBLAx1A0aaW
            Aja5MJRB9xX4pWUOesurk+kXQm3wvzXuc0hNN6Xme2yhCHcDSEK4yHNyTz4RsyVx
            QFQiPtCekon+vq93yNsWRZHim22VXIFxp4+rUl05MXcC/Wc47zWDtCx0Xtd9ljZ7
            kssY2f71gu8qx3/FMD27dgMlIjU4NnVk5eCPVg8KN6ocgkquCQQ7oPhpxjUo1ct8
            FOlsZrhiklU2bdsNhfJCeOxQAzFvMu5r5AN6GomE6Oc/EuM2LFeEv5VTWnhsMgdl
            jBV82cAPRzpYDy36NZ4bPrkrXKGrLkrjB3pwJTKxlSbz2KCt5MlD1XfDiJrWlSMd
            zlhG2Rg0JcXBmX33Vpu91GYBCQIQDgc8DVLPfTURpts0IMxuJwxwBx/BiJAmlNR6
            EpXlNcoNRksT3uSJckPXb1vKt2ir/S2GXBz+upldhNWP6rmSijbEml4JLjyFs34M
            5hrd7AJXo36ULaD0UjjZO5uklhqes5I=
            =iwLu
            -----END PGP MESSAGE-----
          fp: 64CFCFB68E008B4FFDC5C57E27DF86C53A53C621
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
