apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:4sdpkdQ6euEAyML4cNoXK2dZUzcyJy1hYQ==,iv:HU0xe32xi/5e9FCqdAhUDvbF4Ffbh4wNxgyJ25dmu5Y=,tag:PKld3UVFbr8ztSY+54CSug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-24T12:40:40Z"
    mac: ENC[AES256_GCM,data:LhnRGx3bPSGREI7ej8LgW2K5POsq1UyZKsn2vSK9xdToMI5jfsO+rdjtsU6f8t/b5J8XDRKFprWieKwfAGmf/6uvhPgRG/MA6jXcd0+NxneNi8ZVMij05nZ+W69mKNa/2lW9+ud86r3vDDSGgQB/FXOpn9aOhxQtYEEbEz3sxkA=,iv:JZ1HCGWJhywS9zEdLWcrUX4jgCxAIbu0AVJEpeCz86M=,tag:KhKisdzqQBf0W35aKinNvQ==,type:str]
    pgp:
        - created_at: "2025-06-24T12:40:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5HoJ2znURNRAQwAjR3tDe4Nek8I1mYRQo0XiqVombQ3GrPybBDexHagm0V3
            h15iYdz5FmW4zaL1NNhYjkZOzTwMO+joFZ3COo2BeFFHnaYWlP7Smt79tJQ63ujT
            66RghxFUYVCc1ZM1PEYYrdxyNUPlo5K2klR96BDR/CTa984jyXo8yIO2Yd0VL/JT
            F1jS56bUGiA9jbDWNqt1Xag49dtcDj0JuddlkvaJdfdzCLJ5GAkGPA7Zlg2qhIzS
            AvaPM1mttk8PwmjbCME6A4PDQmtARS5Tj+Tm5v7j0I8P4Vq87KtGmRxIr1Eh8kJB
            i4Tul8tmFyjeaDOZsah2tMAZ+VvEE55rwMYDAOr9sFfM2YR2AHvzRfM1FcENFmf8
            mGiULW6+D15jdyVq2/Avd1Kx/hGQMLepGznPiDYrMCBizHp2UlgQxzNpZ6JdyJ82
            l1SAOUUsTdvWmNWJRSPICeP/ILTD9GYaRJg/6akRh93cPUY/9lCnvEmQjNHa8Wrd
            VQOjJXBqxEnKe4uLLABj1GgBCQIQGAPGlLT5hhYYyZiS5RcY+i1xMykQHWW6vAW0
            nvOHGHLfEE4C6BUK/ZA8n9hKwxJwhpWsDgfIGKwgANjS1yMYcojSHo6a8kkPyLum
            Bq0cealUZKGnpAuY/kDUiBttRl6g+icgeg==
            =Eccs
            -----END PGP MESSAGE-----
          fp: 41F3B1ED2F5FFB3A9D7C6539628B24399345BA10
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
